import type { Metadata } from "next";
import { Josefin_Sans, Josefin_Slab } from "next/font/google";
import "./globals.css";
import { AppWrapper, BottomBar, TopBar } from "@/components";
import { ModalProvider, UIProvider, Web3Provider } from "@/providers";

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

const josefinSlab = Josefin_Slab({
  variable: "--font-josefin-slab",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable} ${josefinSlab.variable} antialiased dark text-foreground bg-background`}
      >
        <UIProvider>
          <Web3Provider>
            <ModalProvider>
              <AppWrapper>
                <TopBar />
                {children}
              </AppWrapper>
              <BottomBar />
            </ModalProvider>
          </Web3Provider>
        </UIProvider>
      </body>
    </html>
  );
}
